# Generated by Django 5.0.6 on 2024-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0004_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
