# Generated by Django 5.0.6 on 2024-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0005_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
