# Generated by Django 5.0.6 on 2024-07-08 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="users",
            field=models.ManyToManyField(
                related_name="organizations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
